#41 Add new GitHub Actions workflow to submit dependency tree samples
FwMotion/3scale-cms pull request #66
Opened 2023-10-07 19:08 UTC by Monoradioactivo

This PR adds a new GitHub Actions workflow that updates our dependency graph whenever there's a change to pom.xml in the main branch

2023-10-07 20:51 UTC, rmgrimm requested changes

2023-10-07 20:51 UTC, rmgrimm commented on .github/workflows/submit-dependency-tree-samples.yml
> +        uses: actions/checkout@v2
Please use the latest version of `actions/checkout`, namely v4

2023-10-07 20:51 UTC, rmgrimm commented on .github/workflows/submit-dependency-tree-samples.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
This is unnecessary, because the `advanced-security/maven-dependency-submission-action` defaults to using the GitHub token. Because it's the same as the default, please leave this part out.

2023-10-08 20:18 UTC, Monoradioactivo commented on .github/workflows/submit-dependency-tree-samples.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
Done, please review.

2023-10-08 20:19 UTC, Monoradioactivo commented on .github/workflows/submit-dependency-tree-samples.yml
> +        uses: actions/checkout@v2
Done, please review.

2023-10-08 20:42 UTC, rmgrimm approved these changes
Looks good. Thanks for the pull request, @Monoradioactivo !

2023-10-08 20:42 UTC, merged